##
## Makefile for Makefile in /home/lak_r/rendu/Semester4/Unix_prog/PSU_2016_myirc/Lib
## 
## Made by remi
## Login   <remi.lak@epitech.eu>
## 
## Started on  Tue May 30 13:51:19 2017 remi
## Last update Thu Jun  8 20:17:01 2017 minikali
##

all:
	$(MAKE) -C utils

clean:
	$(MAKE) -C utils	clean

fclean:
	$(MAKE) -C utils	fclean

re:	fclean all

.PHONY:	all clean fclean re
